version: '3.1'
services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=P@ssw0rd
    ports:
      - "27017:27017"
    command: mongod
